### ISSUE TITLE
Current emoji code doesnt support animated emojis. 

### ISSUE THREAD

**Issue by SquirrelKiev** [DenisD3D/Mc2Discord#102]
### Describe the bug

![image](https://github.com/DenisD3D/Mc2Discord/assets/41798511/bb889fcd-d659-48d1-b6d1-53dd8926b30c)
![image](https://github.com/DenisD3D/Mc2Discord/assets/41798511/32c71e0e-d6e1-484a-841a-5aa5e1e3c78b)

**Comment by SquirrelKiev** [comment]
(on the topic of emojis, I don't believe Emojiful supports emojis with capitals in? correct me if i'm wrong but i think the emoji would have to be lowercase'd before being sent into the Minecraft chat in order to be picked up by Emojiful.)

**Comment by DenisD3D** [comment]
Indeed from you screenshot it appear that the animated format has an additional a. As I'm not a nitro membre I wasn't aware of it. I'm gonna fix this in the next version of the mod

**Comment by SquirrelKiev** [comment]
if it helps, regex for `ANY_DISCORD_MENTION_PATTERN` in `M2DUtils` could be `<a?(?::\w+:|@&*|#)\d+>`, and line 111's regex in `M2DUtils` could be `<a?:(\w+):\d+>` and you'd be pretty much set

**Comment by SquirrelKiev** [comment]
also, im aware its not the primary topic of the issue report but i still wanna mention it anyway, I don't think Emojiful allows emojis with capitals in? When I tried adding emojis with capitals they simply didn't appear in the emojiful selection, and the official emojiful datapack creation bot in the emojiful Discord also lowercases every emote name. 
I'm bringing this up here as this means any emotes with capital letters in that are sent in discord chat wont appear correctly in game. Lowercasing the emoji name shows up fine, however. (screenshots are from a fork where the emojis are lowercased before being sent)
![image](https://github.com/DenisD3D/Mc2Discord/assets/41798511/c8fd1517-f942-442d-8c9d-ce1ae9122bff)
![image](https://github.com/DenisD3D/Mc2Discord/assets/41798511/e62ddeb0-2bba-4648-9422-44a7a8f3d510)
![image](https://github.com/DenisD3D/Mc2Discord/assets/41798511/54782e7e-c553-4391-ba11-1ec90d41c7e2)
