### ISSUE TITLE
[1.12.2][Feature Request] Ignore cancelled chat events

### ISSUE THREAD

**Issue by Krutoy242** [DenisD3D/Mc2Discord#103]
Please implement this PR into Mc2Discord:
### https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/pull/556

The issue is described [here](https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/issues/555). 

I know 1.12.2 is in low priority, but its actually just a two lines of code, so I believe 🙏 

On my server its looks like this and kinda annoying:
![image](https://github.com/DenisD3D/Mc2Discord/assets/936618/080e7ef1-73e4-4570-b0da-322c9597faa1)

**Comment by DenisD3D** [comment]
Canceled event should already be ignored (at least in 4.x not sure in 3.x), I can set the lowest priority in next version

**Comment by Krutoy242** [comment]
Feature is still actual and appreciated!

**Comment by DenisD3D** [comment]
Published as 3.3.2
