### ISSUE TITLE
1.12.2 mod ver 3.2.11

### ISSUE THREAD

**Issue by MiHaPoKi** [DenisD3D/Mc2Discord#104]
### Describe the bug

Minecraft messages in discord show up perfectly, but not vise versa
When i send a message in discord in minecraftit only shows name of user and nothing more
![2024-02-11_23 36 51](https://github.com/DenisD3D/Mc2Discord/assets/121764488/c084984f-6bfe-4641-a0aa-04c6b968e3a4)

Didnt change really much in the config
/mc2discord upload returns fail:
![2024-02-11_23 39 10](https://github.com/DenisD3D/Mc2Discord/assets/121764488/292a5484-ecf1-46cc-b1a2-8264ac9134f7)
pls help

**Comment by DenisD3D** [comment]
1) Please update to 3.2.12 will fix the issue of /mc2discord upload
2) Check for missing message content on discord website (red bullet 3: https://github.com/DenisD3D/Mc2Discord/wiki/Create-a-Discord-Bot#4-configure-the-bot)

**Comment by MiHaPoKi** [comment]
Thank you, ill do stuff in discord developer portal, but i dont have
3.2.12, i only have 3.3.0 and higher

пн, 12 февр. 2024 г., 00:51 DenisD3D ***@***.***>:

**Comment by DenisD3D** [comment]
Sorry meaned 3.3.1
But you can keep 3.2.11 if everything else is working fine for you. The Discord portal fix should be enough

**Comment by MiHaPoKi** [comment]
Okay, thank you!

пн, 12 февр. 2024 г., 00:59 DenisD3D ***@***.***>:
