### ISSUE TITLE
1.20.1 Console Errors? Slow minecraft to discord translation.

### ISSUE THREAD

**Issue by S0ndz** [DenisD3D/Mc2Discord#106]
### Describe the bug

Hiya, recently installed your mod and have been getting quite a lot of issues with communication from minecraft to discord. 
Usually messages sent in minecraft will not be sent until an hour later, at which point all of them are sent at once (so around 100 messages are sent at once)
Trying to upload the config file returns the following error.
![image](https://github.com/DenisD3D/Mc2Discord/assets/127669200/49d22fe3-6a93-4336-a857-04034319f205)
I'm assuming this is an error caused by my firewall possibly?

The server log is sometimes full of errors that I have provided in the github link:
https://pastebin.com/c2WUVwmw

My server is also running in offline mode, could this be affecting performance?

**Comment by DenisD3D** [comment]
Upload error is because you are running on mc2discord v3.x so no worry about that
For the message waiting an hour to be sent I never seen anything like that and don't have anything in the code that could result into that.
Offline mod has no impact on the mod performance

**Comment by DenisD3D** [comment]
After a closer look to the error it's more likely a firewall / host provider issue indeed
