### ISSUE TITLE
Proximity Chat Discord-Minecraft (Enhancement)

### ISSUE THREAD

**Issue by ExplosiveGeek77** [DenisD3D/Mc2Discord#111]
I can't tell you the exact way to add this functionality, but I want you to add the ability to join a VC and you can talk to people in game, when you walk away they will get quieter and closer it gets louder. AKA, full 3D audio/positional audio.

https://modrinth.com/plugin/simple-voice-chat with https://modrinth.com/plugin/simple-voice-chat-discord-bridge, https://modrinth.com/mod/discord-proximity. I don't know if plugins will be particularly helpful for you but https://www.spigotmc.org/resources/discordsrv.18494/ does this and https://www.spigotmc.org/resources/skoice-proximity-voice-chat.82861/ also does this, and it does it really well. These are the only ones I could find right now. All these options can do what I want but the problem is many of them aren't updated to 1.20.6, which is what my server runs on, and discordsrv and skoice both don't have positional/3D audio support. I also like you discord integration a lot so I am interested in this feature among the others.

**Comment by DenisD3D** [comment]
Hello,
This feature can't be implemented. Here's why:
- Simple Voice Chat is independant from Discord. It's a voice server on it's own. Doing the same thing is outside of the scope of this mod as not Discord related.
- Simple Voice Chat Discord Bridge is a support for the few users that don't have the mod install (requires a voice channel by user)
- Discord proximity doesn't work anymore (Discord deleted the feature)
- DiscordSRV use a system of group. This imply no fading for player when they are far (and then directly being disconnected).
All in all, I don't think this feature is really usuable considering Discord limitations and I also think it's out of the scope of the project (a text chat bridge)
