### ISSUE TITLE
Feature Request: Add sleep message channel

### ISSUE THREAD

**Issue by josef-dijon** [DenisD3D/Mc2Discord#117]
I've recently added mc2discord to my server, and it is awesome!

However, when things are quiet, discord is spammed with "<player> went to sleep. Sweet dreams!" which is not something that anyone else not playing will find useful.

Can we get a new "sleep" channel for filtering these messages out?

**Comment by DenisD3D** [comment]
This must come from another mod you are using. Maybe you can disable this mod message?
Looks like a x players need to sleep for the server to sleep to the morning. But that do it automatically if there is no player online.

**Comment by josef-dijon** [comment]
Ah yes, you are totally right. I've had the vanilla tweaks multiplayer sleep datapack enabled for so long, I didn't realise that sleep message wasn't vanilla!

Thanks for your quick response and keep up the great work!
