### ISSUE TITLE
(Feature request) make bot ignore certain players

### ISSUE THREAD

**Issue by Nasty289** [DenisD3D/Mc2Discord#119]
I have a moderator account that I use on my server, which also has a /vanish option, which stops the join / leave message from showing.
However, the bot still shows me log on and off, which defeats the purpose.
If it'd be possible, I'd want the bot to ignore the join / leave message just from that one mod account.

In game chat:
no join message
![image](https://github.com/user-attachments/assets/ef80ab85-b5f3-413b-82b6-a5618718e9ed)

Discord chat:
join message
![image](https://github.com/user-attachments/assets/1fcb129d-61d4-4764-b9b9-621413a24c98)

I've tried setting up the username as a banned word so it get's blocked in general, however the AutoMod ignores the bot

**Comment by DenisD3D** [comment]
You can use /mc2discord hidden add yourname yo completely hide yourself from the mod.
This vanish mod have an integration that hide yourself automatically https://www.curseforge.com/minecraft/mc-mods/vanishmod

**Comment by Nasty289** [comment]
Ah, yea seems that flew over my head, thanks :D
