### ISSUE TITLE
mc2discord doesnt work with Neoforge

### ISSUE THREAD

**Issue by sprocketaudio** [DenisD3D/Mc2Discord#124]
### Describe the bug

On Curse mc2discord-forge-1.20.x-4.2.1.jar is labelled as forge and neoforge, but loading it in neoforge 21.1.42 doesnt do anything or produce a config file.

![image](https://github.com/user-attachments/assets/6a1e0169-f938-4920-84fa-981ea52a7438)

**Comment by DenisD3D** [comment]
Hey, 
Mc2discord-1.20.x is intended for mc 1.20.0 and 1.20.1
If I recall correctly neoforge 21.1 is intended for 1.21.1
Only the first versions of neoforge where compatible with forge versions. That not the case any more and I haven't had the time to make a neoforge version yet. 

Conclusion : mc2discord is not compatible with neoforge in 1.21.1 for now
