### ISSUE TITLE
[1.12.2] Trace log spam

### ISSUE THREAD

**Issue by Krutoy242** [DenisD3D/Mc2Discord#127]
### Describe the bug

Mc2Discord flooding debug.log file with meaningless trace.
This is happens when players chatting in other channels of discord - MC server will log a message for each text message in discord server, even if this happen in "general" or other channels, not channel that picked for MC <=> Discord comunication.

This log data should be completely removed and not even traced, since MC dedicated server should not care what happens in other Discord channels except linked one.

![image](https://github.com/user-attachments/assets/a9a8e43d-ac3a-4a14-b169-b25d75d087bd)

[debug.log](https://github.com/user-attachments/files/17276629/debug.log)

### Your config file

http://m2d.denisd3d.fr/uploads/view?key=3be3c3ac-0694-425b-9b11-91795e959213

**Comment by DenisD3D** [comment]
Hello,
debug.log file is supposed to contain as much information as possible. That's why those message are included.
Maybe they can indeed be removed, however I'm not actively maintening 1.12.2/3.x version of the mod anymore
Denis
