### ISSUE TITLE
Intermittent Double Advancements in discord

### ISSUE THREAD

**Issue by Mx772** [DenisD3D/Mc2Discord#55]
This may be a duplicate of #47. However, I'm on 3.1.2, so it should be fixed.
mc2discord-forge-1.16.x-3.1.2.jar

Logs aren't showing any errors. Have Webhook mode on. Worked fine on 3.1.0. 

### Intermittently double messages:
![image](https://user-images.githubusercontent.com/9059161/136977985-e4aba425-ba43-4dc9-854e-3a307ac85c28.png)

Most config here is default:

```
	[[Channels.Channel]]
		id = 123 (fake)
		subscriptions = ["info", "chat"]
		use_webhook = true
```

Sidenote: it logs the following even while on 3.1.2:
New version available: 3.1.2

**Comment by DenisD3D** [comment]
Self solved / solved on discord
