### ISSUE TITLE
User Avatars not loading consistently

### ISSUE THREAD

**Issue by Mx772** [DenisD3D/Mc2Discord#56]
### Intermittently missing heads:
![image](https://user-images.githubusercontent.com/9059161/136977718-664184d0-8c55-488f-9e77-dba433e3b60a.png)

Within a minute of eachother:
![image](https://user-images.githubusercontent.com/9059161/136977908-631199b7-ff56-48fd-a9f3-797151414e99.png)
![image](https://user-images.githubusercontent.com/9059161/136977920-981ec5d4-972a-4324-a9a6-bb4f4e79c448.png)

mc2discord-forge-1.16.x-3.1.2.jar

Most config here is default:

```
	[[Channels.Channel]]
		id = 123 (fake)
		subscriptions = ["info", "chat"]
		use_webhook = true
```

**Comment by DenisD3D** [comment]
Hi, thanks for your issue
As for the other issue, this got reported on discord a few days ago :)
Head is managed by a 3rd party api. It must be there side failing. About a year ago, many users got this issue and it self-solved after a few and me being banned from their discord for reporting the issue :( 
You can easily swap for another head api in the config with the avatar_api but mc-heads was the better i found

**Comment by DenisD3D** [comment]
Self solved / solved on discord
