### ISSUE TITLE
[1.18.1] Messages sent by "say" command in console doesn't get sent to discord.

### ISSUE THREAD

**Issue by Gbergz** [DenisD3D/Mc2Discord#59]
Title ^  (could affect other versions aswell)

## Info
Typing anything into console w/ the "say" command will not relay the message to discord. Nothing shows up at all.

## Versions:
MC: 1.18.1
Forge: 39.0.5
MC2Discord: 1.18.x-3.2.2

**-** Gbergz

**Comment by DenisD3D** [comment]
Indeed. Some internal change of forge / mc broke the command. That's now fixed in 3.2.3
Thanks you for reporting the issue
