### ISSUE TITLE
Color codes MC -> Discord

### ISSUE THREAD

**Issue by SirDoof** [DenisD3D/Mc2Discord#60]
Hi,
So color codes appear in the chat in Discord if you type with color codes in-game. Happens with either `§` or `&`.
Example Output --> &b&lTest
Is it possible to remove those and keep only the text? Would be greatly appreciated if so.
Thank you!

**Comment by DenisD3D** [comment]
I add this on my todo list for next version
This shouldn't be a problem as it's already removed from command

**Comment by DenisD3D** [comment]
Fixed in 3.2.4
