### ISSUE TITLE
[Suggestion] Any way to prevent color codes showing up as "§7" when translated to discord? (example attached).

### ISSUE THREAD

**Issue by Gbergz** [DenisD3D/Mc2Discord#64]
So, 
Any way to prevent color codes showing up as "§7" when translated to discord? Looks pretty ugly 😅
![image](https://user-images.githubusercontent.com/26634554/181935981-95171e40-226e-4ef4-b357-3dbee9f12f8c.png)

Entries in the configs:

```
	# Global variables, Player variables and Advancement variables
	advancement = "${player_name} has made the advancement: §8[${advancement_title}]§7\n${advancement_description}."
```

Shows up as intended in-game but when translated to discord it shows like what's in the screenshot above.

**-** Gbergz

**Comment by DenisD3D** [comment]
Hi, modifying this config value doesn't impact the ingame message but only the discord one so you can remove the color code without any impact in-game. I still can remove colors codes from discord message if you really want to

**Comment by Gbergz** [comment]
Well if I remove the color code then it isn't colored ingame anymore like I wanted ..
That's why I reported this 😅

**Comment by DenisD3D** [comment]
The advancement value in the config only impact the Discord message. The Minecraft behavior isn't modified from the vanilla game.
Here's an exemple with the following config (same as your but with removed color code)
```toml
advancement = "${player_name} has made the advancement: [${advancement_title}]\n${advancement_description}."
```
![image](https://user-images.githubusercontent.com/35769613/182204463-86a51cbd-8bdd-4278-99b7-6d08438a3f03.png)
![image](https://user-images.githubusercontent.com/35769613/182204435-645298a1-a212-4c79-9eab-80ef14557f0e.png)

So you can remove the color code in the configuration without impacting the ingame look
Denis

**Comment by Gbergz** [comment]
Yes but I don't want to remove the color, I just don't want the color codes showing up in the discord message
![image](https://user-images.githubusercontent.com/26634554/182206809-74ecd98a-b1d4-47ae-b3d0-e396f558a085.png)

like here, if possible.

**Comment by DenisD3D** [comment]
I don't really understand why you don't want to remove them as the only effect they have is to be printed on discord

**Comment by Gbergz** [comment]
That message makes it gray and light gray in-game, but translated to discord its §8 and §7

**Comment by DenisD3D** [comment]
Could you send a screen of the result with color ingame ?
It's not possible to have the advancement value in the config being on Minercaft
So the color code can't be processed by Minercaft as the message isn't displayed. Mc2Discord doesn't change the default ingame message.

The color code are already removed in some variables. This can be extended to remove § from whole messages but would limit people to use § in all discord. While it will never be used by Minecraft in the advancement case, you can just remove it.

Please send a screen from ingame with the gray and light gray.

**Comment by Gbergz** [comment]
Ah right, sorry- probably should've mentioned that I have multiple servers using the same mod with different bots, sending messages across servers. Using 	`relay_bot_messages = true`. And a message coming from one server onto another will have the §8 and §7 colors showing there. But in discord it'll show like in the screenshot above with §8 and §7 included.

**Comment by DenisD3D** [comment]
That's changing a lot of things 😄. The result is still the same. If I remove the color code on Discord, then the second server will recieve the message without the color code and won't color the message on the second server.

**Comment by Gbergz** [comment]
Ah, oh well! Not much to be done then. Thanks for replying atleast :)
