### ISSUE TITLE
Crash when opening using the Singleplayer Integrated Server

### ISSUE THREAD

**Issue by scmcgowen** [DenisD3D/Mc2Discord#65]
### Describe the bug

When the mod is installed on the client, the game crashes with a NullPointerException
[crash-2022-08-10_13.37.38-server.txt](https://github.com/DenisD3D/Mc2Discord/files/9303904/crash-2022-08-10_13.37.38-server.txt)

The Integrated Server should be able to run perfectly fine, in case a modpack dev puts Mc2Discord into the modpack client side or if I use the Integrated Server to test before deploying to production

### Your config file

N/A

**Comment by DenisD3D** [comment]
Thanks for reporting! The mod shouldn't crash on client. The current behavior (before the version that introduced this issue) is to do nothing thing if the server isn't started

**Comment by DenisD3D** [comment]
Thanks for reporting! The mod shouldn't crash on client. The current behavior (before the version that introduced this issue) is to do nothing thing if the mod is installed on client.
If you need the mod client side, I can consider adding support for it

Ps: soory for the misclick / issue close&reopen

**Comment by scmcgowen** [comment]
Adding integrated server support would be nice for testing

**Comment by DenisD3D** [comment]
Are you testing your modpack with the integrated client or are you developing using mc2discord?

**Comment by scmcgowen** [comment]
Modpack, I am the Datapack Developer for a modpack who has a server and I like to set configs up before sending to the server owner using the integrated server.

Also our players have been complaining that singleplayer crashes the game when they open a world and I have confirmed. Thats the #1 priority for me, SP testing is next

**Comment by DenisD3D** [comment]
Fixed in 3.2.10
The client shouldn't crash any more and the mod will work like on the server too. The configuration file will be located in .minecraft/config/mc2discord.toml
Denis
