### ISSUE TITLE
Custom Emoji comptability 

### ISSUE THREAD

**Issue by h4vok-git** [DenisD3D/Mc2Discord#66]
I have an issue regarding custom emojis using the Mc2Discord mod whilst using the Emojiful mod I can use all the emojis that the emojiful mod can use ingame and they will also show up in server too (except for the additional emojis that the mod uses but discord doesnt have such as :saluting_face: as discord still uses an older version of twemoji than the mod) However when it comes to custom emojis that can be added to emojiful mod via datapacks they will appear ingame as expected but will not show up in the server via the bot. From my understanding the bot just forwards the plain text that was added from the server and since the normal emojis are part of unicode or discord allows bots to just type up the emoji like normal due to this they are passed through with no issue however custom emojis don't as i think the bot doesn't take into account the custom emoji ID which has to be directly referenced in order for the emoji to show up through a bot (refer to this: https://stackoverflow.com/questions/51982806/how-do-i-make-my-discord-py-bot-use-custom-emoji). 

You can see the steps to reproduce this from the following screenshots: 
using normal emoji: works both ways also works if i post an emoji ingame it will appear in server and if i post emoji in server it will appear ingame.
![image](https://user-images.githubusercontent.com/84686040/186999391-ab7bca3c-0aa8-46e9-90c1-63aa483eef49.png)
![image](https://user-images.githubusercontent.com/84686040/186999500-644fb49b-8d1c-4aa7-99c4-08340beb2ca2.png)
![image](https://user-images.githubusercontent.com/84686040/186999521-566202aa-710d-41ed-93a6-1e9c94287291.png)
![image](https://user-images.githubusercontent.com/84686040/186999664-eeb8e7ba-8daf-4f46-b9b2-ec8f3b1b6738.png)
![image](https://user-images.githubusercontent.com/84686040/186999675-6ac067f1-b046-41c2-b3ff-f2166559b9ff.png)

using custom emoji i added via datapack: (additional info on adding custom emoji on emojiful mod page https://www.curseforge.com/minecraft/mc-mods/emojiful) 

posting custom emoji in discord: as can been seen i can see the emoji in game when i post it through discord
![image](https://user-images.githubusercontent.com/84686040/186999799-409ef813-d525-4641-b8a0-95fe66d03e51.png)
![image](https://user-images.githubusercontent.com/84686040/186999804-44c1f7da-2dbc-4228-bb77-1799c6b768ad.png)
![image](https://user-images.githubusercontent.com/84686040/186999850-a8baf9cc-cee7-4b9a-bc00-d972866e0a8b.png)

posting custom emoji in game: as can been seen i can see the emoji in game but the emoji doesnt show up in discord

![image](https://user-images.githubusercontent.com/84686040/187000036-57d1daa8-8323-4b98-85c2-00dc19edb7fc.png)
![image](https://user-images.githubusercontent.com/84686040/187000053-d0ba45ae-fc60-4f95-a9f3-1b9f3ffd4722.png)
![image](https://user-images.githubusercontent.com/84686040/187000078-9e08f09b-c89c-4049-99d8-69aae082d77e.png)

steps to reproduce: 
- install ur mod and set up as you would 
- install emojiful on server
- create a custom emoji datapack and have same emoji in server that the mc2discord mod is in
- use custom emoji in game and check discord for what the bot returns 
- bot will return plain text instead of emoji

I know this is a very niche issue and the solution may be more complex than just checking for the emoji ID for custom emojis but i would really appreciate if you could fix this if you would like any additional information msg me on discord: H4VØK#9955

emojiful source code: https://github.com/InnovativeOnlineIndustries/Emojiful

versions:
mc2discord-forge-1.16.x-3.2.10
emojiful-1.16.4-2.1.4
forge 36.2.20 (1.16.5)

**Comment by DenisD3D** [comment]
Will look into it

**Comment by DenisD3D** [comment]
Added in 3.3.0
