### ISSUE TITLE
`top_role` color is black when top role has no color.

### ISSUE THREAD

**Issue by SwanX1** [DenisD3D/Mc2Discord#67]
### Describe the bug

On Discord the color of the member is the top role **with** a color. Mc2Discord uses the top role regardless of whether it has a color, and when it doesn't, it defaults to `#000000`

![In-Game chat](https://user-images.githubusercontent.com/36593309/191103439-6509d732-7261-4b1c-a69d-03d8775927f6.png)
![Discord-linked chat](https://user-images.githubusercontent.com/36593309/191103508-f5eaedc1-eb78-4384-915b-a2b28a0d2e52.png)

`Swan#7488`'s top roles: 
![see above](https://user-images.githubusercontent.com/36593309/191103919-040f0232-d52c-40fc-bc5c-0fe59705b08d.png)

`IcyCrystal#0872`'s top role:
![see above](https://user-images.githubusercontent.com/36593309/191103730-e231641c-30b2-41f6-8512-553162a7a0b0.png)

### Your config file

http://m2d.denisd3d.ml/uploads/view?key=5ddc14e0-dd0c-4dc0-ab39-1c27d2e3cd68

**Comment by SwanX1** [comment]
Possible solution in code

PartialMember.java Line 140
```diff
- messageCreateEvent.getMember().get().getHighestRole()
+ MathFlux.max(messageCreateEvent.getMember().get().getRoles().filter(role -> role.getColor() != 0), OrderUtil.ROLE_ORDER))
 .map(Role::getColor).map(Color::getRGB).defaultIfEmpty(16777215).subscribe(integer -> {
```

No idea if this works, I wrote it looking at Discord4J's code and writing this straight in here.

**Comment by DenisD3D** [comment]
Yes was on that too :)
If you want to make a PR there is an Github Action to compile the mod without installing any dev tools.
I may not be able to do the edit myself for the next week or so

**Comment by SwanX1** [comment]
I've opened PR #68 that fixes this issue
