### ISSUE TITLE
Null Pointer Exception 

### ISSUE THREAD

**Issue by Valvify** [DenisD3D/Mc2Discord#69]
### Describe the bug

Server Log:
https://gist.github.com/Valvify/d377ff38361e09aab044cab91efd27ed

Config File:
https://gist.github.com/Valvify/6d7b7de9c8616d0f8a66b6f9ee8dd8f4

Would also like to know how I can allow someone on Discord to use any command rather than just select ones. Thanks!

**Comment by DenisD3D** [comment]
Hi,
Which mc version are you using ?

For allowing all commands you can set the permission_level to 4 rather to -1 (-1 meaning none, other value being mc permission level)

Denis

**Comment by Valvify** [comment]
Minecraft 1.16.5 and Forge 36.2.26

**Comment by DenisD3D** [comment]
When does this happend (i.e. server boot, every x minutes) ?
Is it just a console error or does it have more effect (e.g. server crash) ?
Does the bot show the number of players in its presence message (playing at message) ?

**Comment by Valvify** [comment]
It happens on server boot, once it's ready.

It seems to crash the server or at least overload it because I'm unable to join. It keeps sending that same crash log in the console. The bot does show as online when the server is on and has the correct presence message.

**Comment by DenisD3D** [comment]
Does the bot status show as playing or competing ?
The error might be comming from the type = "COMPETING" in your presence message config. Try to revert it back to the default PLAYING value. Maybe Discord doesn't allow this value anymore.

**Comment by DenisD3D** [comment]
Will investigate

**Comment by DenisD3D** [comment]
Hi,
I'm curently investigating for your issue and i can't manage to find the causes. 
Could you try switching off the logging features to see if it resolves the issue ?
Could you also provide the server provider you are using to host server ? (Name of the provider, could also be your own computer)
Thanks 
Denis

**Comment by Valvify** [comment]
Hi there.

I won't be able to help you with the first question just yet; I'll get back in touch.

As for the server provider, I'm hosting my own instance using Oracle Cloud. Ubuntu 22.04.1 LTS, aarch64

**Comment by DenisD3D** [comment]
Fixed 4.0.0
