### ISSUE TITLE
Error Message - 1.16.5

### ISSUE THREAD

**Issue by Foxydapirate12** [DenisD3D/Mc2Discord#73]
### Describe the bug

Hello, i've been getting this error message and am curious as to why and what it means, message here: [ [WARN] (ml.denisd3d.mc2discord.repack.reactor-http-nio-3) Error while decoding JSON (java.lang.IllegalArgumentExceptionAttempt to deserialize payload with unknown event type: GUILD_AUDIT_LOG_ENTRY_CREATE): {"t":"GUILD_AUDIT_LOG_ENTRY_CREATE","s":34,"op":0,"d":{"user_id":"381593109236154381","target_id":"1076858800902000640","id":"1076858800902000642","changes":[{"new_value":"changlelog","key":"name"},{"new_value":0,"key":"type"},{"new_value":[{"type":0,"id":"1016801975670677648","deny":"517544007680","allow":"65536"}],"key":"permission_overwrites"},{"new_value":false,"key":"nsfw"},{"new_value":0,"key":"rate_limit_per_user"},{"new_value":0,"key":"flags"}],"action_type":10,"guild_id":"1016801975670677647"}}

Also when i run /mc2discord upload it gives this: Upload failed : Unexpected response status: 203

### Your config file

https://gist.github.com/Foxydapirate12/c77d519e727b689f81215cac96101ff7

**Comment by DenisD3D** [comment]
You can safely ignore this warning. Sometimes Discord add new messages to the api for a few days before removing them :(
It should disapear soon

For the /mc2discord upload, the server is down for now. I will put it back up soon

**Comment by Foxydapirate12** [comment]
Ahh ok thanks!! ^^
