### ISSUE TITLE
Discord > MC not working as intended. [1.19.2]

### ISSUE THREAD

**Issue by MoonstruckSpirit** [DenisD3D/Mc2Discord#74]
### Describe the bug

# Client Information

**Mod Version:** 3.3.0
**Forge Version:** 43.2.7
**Game Version:** 1.19,2

## Description of the bug

When I type in the Discord chat, it sends the username/nickname but not the message content. It works fine from MC to Discord though.

## Extra Information

![Proof of message in Discord](https://user-images.githubusercontent.com/105180230/227529954-c3d199ab-f5f5-4e46-b5bd-4f4b98e97257.png)
![Proof of bug in Minecraft](https://user-images.githubusercontent.com/105180230/227530034-d528b5cd-2157-447b-a345-eefc4d78aba1.png)

### Your config file

https://hastebin.com/share/zukutadoco.ini

**Comment by DenisD3D** [comment]
You must be missing he message content intent. See red bullet 3 here : https://github.com/DenisD3D/Mc2Discord/wiki/Create-a-Discord-Bot#4-configure-the-bot
Please reopen if this doesn't solve your issue
