### ISSUE TITLE
Quark Item Sharing Module Configuration

### ISSUE THREAD

**Issue by Fusionpro** [DenisD3D/Mc2Discord#76]
Greetings,

The Quark Item Sharing Module (vazkii.quark.content.management.module.ItemSharingModule) links to Discord chats, even when the chat permission is not specified in the configuration toml file. 

Item sharing should be treated as a CHAT permission, and not an INFO command that is forwarded to Discord.

**Comment by DenisD3D** [comment]
Will rework that part of the mod in the next version
Thanks for reporting

**Comment by DenisD3D** [comment]
Add in 4.0.0
