### ISSUE TITLE
The mod still sends messages even if the message was canceled

### ISSUE THREAD

**Issue by SirEndii** [DenisD3D/Mc2Discord#77]
### Describe the bug

A few users have reported that the messages which were [canceled](https://github.com/SirEndii/AdvancedPeripherals/blob/63139d1dc010ae4a7af141d185ce7cc64156e443/src/main/java/de/srendi/advancedperipherals/common/events/Events.java#L85) by the chat event from [AdvancedPeripherals](https://docs.intelligence-modding.de/peripherals/chat_box/) are still being sent to the Discord chat

A solution would be to lower the priority of the chat event and then check if the event was canceled
I would contribute with a pull request, but I don't really have the time for that currently

**Comment by DenisD3D** [comment]
Will look into it
Thanks for reporting

**Comment by DenisD3D** [comment]
Fixed in 4.0.0
