### ISSUE TITLE
Add command list

### ISSUE THREAD

**Issue by ksk-waqs** [DenisD3D/Mc2Discord#78]
Hi, please add a list of all available commands. How are we supposed to figure out what commands are available if there are no hints or wiki? 😄

**Comment by DenisD3D** [comment]
Hey,
No list of commands is required because they are all !
All commands you can use in server console can be used in Discord. Even one added by mods

**Comment by DenisD3D** [comment]
For that part the documentation is indeed a bit light
You have some comment before each field that explain how it works
For the account linking you have also this section https://github.com/DenisD3D/Mc2Discord/wiki/Advanced-Configuration#enable-account-linking
And for hidding player you can just do /mc2discord hidden add XXXX to prevent any message related to a player to be sent to Discord

**Comment by ksk-waqs** [comment]
And yet, why should we understand what commands there are through config? (which, by the way, very poorly explains how to lick the same accounts).

Is it difficult to make a page with a list of commands, like:

Command section:
/command name <var> <var|var>

**Comment by DenisD3D** [comment]
No, but documenting a mod like mc2discord take an enormous amont of time that I currently don't have.
Feel free to open a PR to improve the wiki, it will be very appreciated
Denis
