### ISSUE TITLE
mc2discord upload command gives error

### ISSUE THREAD

**Issue by Thomas107500** [DenisD3D/Mc2Discord#81]
### Describe the bug

This is the error it gives when i run mc2discord upload command

![image](https://github.com/DenisD3D/Mc2Discord/assets/49201909/0575b9d7-efd5-4d58-a06c-1d356635da41)

Mod Version: mc2discord-forge-1.18.x-3.3.0

**Comment by Thomas107500** [comment]
ok good to know, thanks

**Comment by DenisD3D** [comment]
Fixed in 4.0.0
