### ISSUE TITLE
Dynmap Integration?

### ISSUE THREAD

**Issue by KinfThaDerp** [DenisD3D/Mc2Discord#83]
Hi! 
Any chance you would add integration for dynmap? By this I mean, sending the dynmap messages to discord. It looks really jarring when you see someone respond to a Dynmap Webchat message without the actual message on discord. I understand if you don't care, but I thought it'd still be worth a try to ask :p

**Comment by DenisD3D** [comment]
Hi,
Latest version of mc2discord (4.0.0/still in beta) should support that!
Fill the very end of the config file, feel free to join the Discord server for any help as I haven't written the documentation yet!
You may download the new version here for 1.19 https://github.com/DenisD3D/Mc2Discord/actions/runs/5545954291 or here for 1.20 https://github.com/DenisD3D/Mc2Discord/actions/runs/5546008414 (under Artifacts)
Denis
