### ISSUE TITLE
[1.19.2-forge]tellraw is not fully displayed on discord

### ISSUE THREAD

**Issue by Kevin50912** [DenisD3D/Mc2Discord#85]
### Describe the bug

I used the tellraw command to tell the value of the scoreboard, but it is not displayed on the discord.

Command:/tellraw @a [{"text":"   當前在線人數: ","color":"gold"},{"score":{"name":"當前玩家數量","objective":"time"},"bold":true},{"text":" 人， 還需 ","color":"gold"},{"score":{"name":"目標剩餘人數","objective":"time"},"bold":true},{"text":" 人即可開始遊戲","color":"gold"}]

<img width="514" alt="image" src="https://github.com/DenisD3D/Mc2Discord/assets/89115624/fb3b4296-5339-4d41-8844-1af6c5d9f930">
<img width="366" alt="image" src="https://github.com/DenisD3D/Mc2Discord/assets/89115624/27de598b-1b88-4498-ae72-514f0d87d062">

(All of the above use Google Translate)

**Comment by DenisD3D** [comment]
If I'm reading your command correctly, only the part coming from scoreboard values are missing? (so score text component being ignored)

**Comment by Kevin50912** [comment]
yes

**Comment by DenisD3D** [comment]
I will fix the issue in next version
Thanks for reporting

**Comment by DenisD3D** [comment]
Fixed version may be found here: https://github.com/DenisD3D/Mc2Discord/actions/runs/5683753275
