### ISSUE TITLE
Log time is not recorded

### ISSUE THREAD

**Issue by Kevin50912** [DenisD3D/Mc2Discord#87]
### Describe the bug

When viewing the log, it is found that the time cannot be recorded after the mod is updated

<img width="683" alt="image" src="https://github.com/DenisD3D/Mc2Discord/assets/89115624/0a1f50fa-5903-4eac-8c09-70c914e52c6a">
Discord Bot:
<img width="784" alt="image" src="https://github.com/DenisD3D/Mc2Discord/assets/89115624/061a121a-ffee-4c22-b71d-874f9150dec1">

(All of the above use Google Translate)

### Your config file

http://m2d.denisd3d.fr/uploads/view?key=4dcda077-1284-494e-91df-88df926e27a0

**Comment by DenisD3D** [comment]
Format has changed, you need to delete the log_format line in the config to update to the new format
