### ISSUE TITLE
[1.12.2] Wrong image message

### ISSUE THREAD

**Issue by Krutoy242** [DenisD3D/Mc2Discord#90]
### Describe the bug

Discord user sending image into chat:

![image](https://github.com/DenisD3D/Mc2Discord/assets/936618/1b57046b-d1e9-465d-8180-15ca3e5ccd2e)

This what players see in game

![image](https://github.com/DenisD3D/Mc2Discord/assets/936618/e6ed73e9-cbb1-47ce-ac82-b0f59ca86b82)

**Comment by DenisD3D** [comment]
You are using the 4.x.x config file with 1.12.2 that doesn't support it yet
Please delete the minecraft_chat_format line in the config to bring it back to default value.

**Comment by Krutoy242** [comment]
Oops, my bad, thank you!
