### ISSUE TITLE
[1.20.1] Formatting not working. Bot name shows in the message & Discord Name doesn't get shown in-game.

### ISSUE THREAD

**Issue by Gbergz** [DenisD3D/Mc2Discord#91]
### What Happened?
Formatting is not working when on "PLAIN_TEXT" mode. (Works on "WEBHOOK", but that option is not ideal for me.)
BOT Name also shows in discord whilst it didn't before.
And, discord name doesn't get shown in-game. It's just invisible.
This wasn't an issue on an older version of the mod I used to use until I decided to update.
And I've tried to "fix" it with configs, no avail. Reporting it as a bug.

### Examples (Images):
![screenshot](https://github.com/DenisD3D/Mc2Discord/assets/26634554/490997ec-2f97-461d-b688-f664006dc8ad)

(Name of users sent from discord is invisible ingame.)
![bild](https://github.com/DenisD3D/Mc2Discord/assets/26634554/afc8cf33-0c4e-4f72-b285-1d4da0ba23af)

### More Info:
It's not formatting this below anymore or any other format.
`> ${player_display_name} left the server.`
`>` doesn't get converted to what is shown in the screenshot on the old version.

Found out when setting 

And the name of the bot always shows while it didn't before.

### Versions:
Forge: 47.1.3
MC 1.20.1
MC2Discord: 4.0.2

------------------

**-** Gbergz

### Your config file (No errors, but I removed my bot key etc so it appears as so.)

http://m2d.denisd3d.fr/uploads/view?key=a4f9e673-6163-4bbf-878f-5e635ab3684c

**Comment by DenisD3D** [comment]
Hi,
The bot showing on discord is a change for 4.x versions
Please use mc2discord formatting variables instead of § : https://github.com/DenisD3D/Mc2Discord/wiki/Variables#formatting-variables
For the > not being formatted is due to it not being the first character of the line

**Comment by Gbergz** [comment]
Gotcha. And for the discord name being invisible ingame then?

**Comment by DenisD3D** [comment]
Please use ${member_display_name} instead of ${member_name}

**Comment by Gbergz** [comment]
Thanks!
Disabling the advancement message like in previous versions (by leaving it blank) still sends a message but its blank.
Any way to completely disable that message now?

**Comment by DenisD3D** [comment]
You can replace "info" by "server_start", "server_stop", "player_connect", "player_disconnect", "player_death" but having some empty message being sent is not an intented behavior and it's already on my list of fix for next update

**Comment by Gbergz** [comment]
Thanks again!
And another question, is there a way for it not to broadcast the /say command I send from the console etc? to chats?

**Comment by DenisD3D** [comment]
No that's currently not possible

**Comment by Gbergz** [comment]
Gotcha I'll leave that here as a suggestion then. :)

Thanks for the answers.

**Comment by DenisD3D** [comment]
Original behavior should be restored in 4.2.1
