### ISSUE TITLE
Server Crash on world load

### ISSUE THREAD

**Issue by Medatur76** [DenisD3D/Mc2Discord#92]
### Describe the bug

I just downloaded the fabric version of the mod and put it into my modded server and got this error
`java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
        at fr.denisd3d.mc2discord.shadow.ml.denisd3d.config4j.Config4J.mapField(Config4J.java:107) ~[mc2discord-fabric-1.20.x-4.1.0.jar:?]`
I tested it on a fresh server as well but got the same error.

Minecraft 1.20.1
Fabric Loader Server Version 0.14.22
Mc2Discord Version [Fabric 1.20.x] 4.1.0
Fabric API (I tried 2 versions) 0.86.0+1.20.1 and  0.87.0+1.20.1

### Your config file

don't have one, the server crashes to fast

**Comment by Medatur76** [comment]
Just incase this helps , I think this is the problematic line: `Field[] var4 = value.getClass().getDeclaredFields();`

**Comment by DenisD3D** [comment]
Will look into it tomorow
Thanks for reporting

**Comment by DenisD3D** [comment]
Issue should be fixed with latest version: https://modrinth.com/mod/mc2discord/version/Gzc2VNGK
