### ISSUE TITLE
Datapacks fail to load when starting a server that has a datapack with a load or tick function installed

### ISSUE THREAD

**Issue by bl4ckscor3** [DenisD3D/Mc2Discord#93]
### Describe the bug

When installing Mc2Discord on a server that has a datapack with a load or tick function installed, a Mixin error will occur, and installed datapacks will not load. Here is an [example datapack](https://github.com/DenisD3D/Mc2Discord/files/12777081/Example.Datapack.zip) which makes this reproducible, as well as the [debug.log](https://github.com/DenisD3D/Mc2Discord/files/12777078/debug.log) file. Note, that the datapack works just fine without Mc2Discord installed. Conversely, when installing just Mc2Discord without the datapack, no errors occur and everything works as expected.

__Observed behavior:__ Installing a datapack with a tick/load function will cause a Mixin error and subsequently, installed datapacks will not load.
__Expected behavior:__ Installing a datapack with a tick/load function does not cause any error, and loads the datapack properly.

Steps to reproduce:
1. Install the datapack
2. Start the server
3. Observe the error in the log as well as the datapack not working

### Your config file

http://m2d.denisd3d.fr/uploads/view?key=139212e2-5dbe-470c-b209-19720833df86

**Comment by DenisD3D** [comment]
Hi,
Thanks for reporting the issue. It seems that a field isn't properly remapped for working outside of dev environnement.
Before I manage to fix the issue, I compiled a version without the issue. Say / Me / Tellraw command from datapacks wont be relayed to Discord but rest of the mod and datapacks should work fine
You can download it here: https://github.com/DenisD3D/Mc2Discord/actions/runs/6370517053

**Comment by RickieGamer** [comment]
Having the same error and the dev build crashes on 1.20.1

**Comment by DenisD3D** [comment]
What crash do you get ? It the same jar with one file removed

**Comment by RickieGamer** [comment]
the mods.toml calls for 1.20.2 specifically, I just cracked open the jar I was already using and changed the mixin json and deleted the command mixin
