### ISSUE TITLE
Msgs go into nowhere

### ISSUE THREAD

**Issue by Necumate** [DenisD3D/Mc2Discord#98]
### Describe the bug

While trying to send msg - nothing happens. Message goes into nowhere. Nor in chat, nor discord.

<html>
<body>

[Server thread/ERROR]: Chain link failed, continuing to next one
--
2152 | java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_7471.method_44862()'
2153 | at fr.denisd3d.mc2discord.fabric.FabricEvents.onChatMessageEvent(FabricEvents.java:40) ~[mc2discord-fabric-1.19.x-4.2.2.jar:?]
2154 | at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:102) ~[fabric-message-api-v1-5.0.7+93d8cb8290-b624de5b4dfd5388.jar:?]
2155 | at net.minecraft.class_3324.handler$ddb000$fabric-message-api-v1$onSendChatMessage(class_3324.java:8538) ~[server-intermediary.jar:?]
2156 | at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
2157 | at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
2158 | at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
2159 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
2160 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
2161 | at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
2162 | at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
2163 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
2164 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
2165 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
2166 | at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
2167 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
2168 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
2169 | at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
2170 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
2171 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
2172 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]

### Your config file

http://m2d.denisd3d.fr/uploads/view?key=d9d8feee-3abc-42cd-9350-b69a1f5c9ff5

**Comment by DenisD3D** [comment]
This version of the mod isn't compatible with 1.19.2 only 1.19.3 or .4
Sorry
